<?php
    get_header();
    get_template_part('templates/home_banner_template');
    get_template_part('templates/service_template');
    get_template_part('templates/simple_template');
    get_template_part('templates/calculator_template');
    get_template_part('templates/testimonial_template');
    get_template_part('templates/partner_template');
    get_footer();
?>